// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: protocol/conn.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConnServer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nickname      string                 `protobuf:"bytes,1,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnServer) Reset() {
	*x = ConnServer{}
	mi := &file_protocol_conn_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnServer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnServer) ProtoMessage() {}

func (x *ConnServer) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_conn_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnServer.ProtoReflect.Descriptor instead.
func (*ConnServer) Descriptor() ([]byte, []int) {
	return file_protocol_conn_proto_rawDescGZIP(), []int{0}
}

func (x *ConnServer) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *ConnServer) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type ConnClient struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nickname      string                 `protobuf:"bytes,1,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnClient) Reset() {
	*x = ConnClient{}
	mi := &file_protocol_conn_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnClient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnClient) ProtoMessage() {}

func (x *ConnClient) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_conn_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnClient.ProtoReflect.Descriptor instead.
func (*ConnClient) Descriptor() ([]byte, []int) {
	return file_protocol_conn_proto_rawDescGZIP(), []int{1}
}

func (x *ConnClient) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *ConnClient) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_protocol_conn_proto protoreflect.FileDescriptor

const file_protocol_conn_proto_rawDesc = "" +
	"\n" +
	"\x13protocol/conn.proto\x12\bprotocol\";\n" +
	"\vconn_server\x12\x1a\n" +
	"\bnickname\x18\x01 \x01(\tR\bnickname\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\";\n" +
	"\vconn_client\x12\x1a\n" +
	"\bnickname\x18\x01 \x01(\tR\bnickname\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msgB/Z-github.com/l3hu4l1/chatroom/protocol;protocolb\x06proto3"

var (
	file_protocol_conn_proto_rawDescOnce sync.Once
	file_protocol_conn_proto_rawDescData []byte
)

func file_protocol_conn_proto_rawDescGZIP() []byte {
	file_protocol_conn_proto_rawDescOnce.Do(func() {
		file_protocol_conn_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protocol_conn_proto_rawDesc), len(file_protocol_conn_proto_rawDesc)))
	})
	return file_protocol_conn_proto_rawDescData
}

var file_protocol_conn_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protocol_conn_proto_goTypes = []any{
	(*ConnServer)(nil), // 0: protocol.conn_server
	(*ConnClient)(nil), // 1: protocol.conn_client
}
var file_protocol_conn_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protocol_conn_proto_init() }
func file_protocol_conn_proto_init() {
	if File_protocol_conn_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protocol_conn_proto_rawDesc), len(file_protocol_conn_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protocol_conn_proto_goTypes,
		DependencyIndexes: file_protocol_conn_proto_depIdxs,
		MessageInfos:      file_protocol_conn_proto_msgTypes,
	}.Build()
	File_protocol_conn_proto = out.File
	file_protocol_conn_proto_goTypes = nil
	file_protocol_conn_proto_depIdxs = nil
}
